language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: heroku
 skip_cleanup: true
 api_key: 
  secure: $HEROKU_API_KEY
 app: diagrama-influencia-obesidade
 local_dir: dist
 on:
    branch: main